### ISSUE TITLE
Remove Jeanette From Execs Section

### ISSUE THREAD

**Issue by nathan-j-lew** [sfusurge/sfusurge.github.io#26]
![image](https://user-images.githubusercontent.com/72537484/147301999-0ae1557d-9857-48d8-a71b-1cb733757434.png)

**Comment by nommerzzz** [comment]
Is there a reason why some of these pictures are super blurry on mobile but some are v crispy?

![B2C0ABDC-D7C5-49EA-93C5-87AA4C5D34A7](https://user-images.githubusercontent.com/94329450/147338667-112cbd3a-d428-491c-9576-4256811cd73a.png)

![CE7184D2-9CB6-4D72-98B3-D5BD89C6D35B](https://user-images.githubusercontent.com/94329450/147338661-86960007-1f4d-4873-990d-01a58799201b.png)


![398AA917-1FF9-42C3-9E50-730347A3FB95](https://user-images.githubusercontent.com/94329450/147338648-1bc2df0c-7b58-4f72-b4f2-6228d81905ef.png)
