### ISSUE TITLE
All buttons should have a hover and active state

### ISSUE THREAD

**Issue by nommerzzz** [sfusurge/sfusurge.github.io#37]

**Comment by nathan-j-lew** [comment]
![image](https://user-images.githubusercontent.com/72537484/147522944-3fd32501-e2a7-4ff9-b9a1-9d06c272b9f8.png)
Add transition to hover state on button (it should be turning orange in this case, darkening to a darker orange on click)

![image](https://user-images.githubusercontent.com/72537484/147522995-6701e1a3-8cc8-4738-98f1-fc216a030deb.png)
Sponsor page "sponsor us" button lacks transitions, hover state and active state (should turn red on hover and darker red on click)

![image](https://user-images.githubusercontent.com/72537484/147523047-37443bbd-5ab5-434b-8570-581a7639cd31.png)
Same transition, hover effect and active state should apply here
